spring:
  application:
    name: hrms
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}/${MYSQL_DATABASE:hrms}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driverClassName: com.mysql.jdbc.Driver

server:
  port: ${SERVER_PORT:8080}
